title: Raksha Varahamurthy
email: rakshav@umich.edu
description: >-
  Applied Scientist | Speech AI | Deep Learning | Researcher

url: "https://rakshasv18.github.io"
baseurl: ""

theme: "minimal-mistakes-jekyll"

minimal_mistakes_skin: "air"  # Light theme with macOS-style vibes

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
  Blogs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      header:
        nav: "main"

  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true

navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Blog"
    url: /blog/
  - title: "Publications"
    url: /publication/
  - title: "Contact"
    url: /contact/

sidebar:
  nav: "main"
  sticky: true

author:
  name: Raksha Varahamurthy
  avatar: /assets/images/profile.jpg
  bio: Applied Scientist | Speech AI | Deep Learning
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/rakshasv18"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rakshav@umich.edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/raksha"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

disqus:
  shortname: "raksha-site"
