title: Raksha Varahamurthy
email: rakshav@umich.edu
description: >-
  Applied Scientist | Speech AI | Deep Learning | Researcher

url: "https://rakshasv18.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true
  Blogs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true

# Navigation links in the top navbar
header_pages:
  - _pages/about.md
  - _pages/projects.md
  - _pages/blog.md
  - _pages/publication.md
  - _pages/life.md
  - _pages/contact.md

# Sidebar settings
sidebar:
  nav: "navigation"
  sticky: true

# Author profile settings
author:
  name: Raksha Varahamurthy
  avatar: /assets/images/profile.jpg
  bio: Applied Scientist | Speech AI | Deep Learning
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/rakshasv18"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:rakshav@umich.edu"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/raksha"

# Markdown and syntax highlighting settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Comments and analytics (optional)
disqus:
  shortname: "raksha-site"
