title: Raksha Varahamurthy
email: rakshav@umich.edu
description: >-
  Applied Scientist | Speech AI | Deep Learning | Researcher

url: "https://raksha.github.io"
baseurl: ""  # Do not change

# Use remote Minimal Mistakes theme (hosted version)
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Enable custom pages and navigation
collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Navigation bar
nav:
  - title: "About Me"
    url: /about/
  - title: "Publications"
    url: /publication/
  - title: "Research and Projects"
    url: /projects/
  - title: "Travel and Life"
    url: /travel/
  - title: "Contact Me"
    url: /contact/
