title: Raksha Varahamurthy
email: rakshav@umich.edu
description: >-
  Applied Scientist | Speech AI | Deep Learning | Researcher

url: "https://rakshasv18.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true

# Navigation bar
navigation:
  - title: "About Me"
    url: /about/
  - title: "Publications"
    url: /publication/
  - title: "Research and Projects"
    url: /projects/
  - title: "Travel and Life"
    url: /travel/
  - title: "Contact Me"
    url: /contact/
  - title: "Blog"
    url: /blog/

# Author info
author:
  name: Raksha Varahamurthy
  avatar: /assets/images/profile.jpg
  bio: Applied Scientist | Speech AI | Deep Learning

# Optional settings
disqus:
  shortname: "raksha-site"

# Social (optional, add links later)
social:
  type: Person
  name: Raksha Varahamurthy
  links:
    - https://github.com/rakshasv18
    - mailto:rakshav@umich.edu

# Theme settings (optional customization)
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
